### ISSUE TITLE
just want to say

### ISSUE THREAD

**Issue by junosuarez** [meandavejustice/butts#1]
:+1: :poop:

**Comment by meandavejustice** [comment]
You make me feel like this guy ![](http://icons.iconarchive.com/icons/artdesigner/emoticons-2/256/cool-icon.png)

**Comment by kid-icarus** [comment]
:moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon: :moon:
